#!/usr/bin/env bash
# Install ufw if not already installed
sudo apt-get update
sudo apt-get install ufw

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow incoming SSH (port 22) traffic
sudo ufw allow 22/tcp

# Allow incoming HTTPS (port 443) traffic
sudo ufw allow 443/tcp

# Allow incoming HTTP (port 80) traffic
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable

