#!/usr/bin/env bash
# Ensure that ufw is installed
sudo apt-get update
sudo apt-get install ufw

# Enable ufw
sudo ufw enable

# Allow incoming SSH (port 22) traffic
sudo ufw allow 22/tcp

# Allow incoming HTTPS (port 443) traffic
sudo ufw allow 443/tcp

# Allow incoming HTTP (port 80) traffic
sudo ufw allow 80/tcp

# Redirect port 8080 to port 80
sudo ufw route allow proto tcp from any to any port 8080

# Reload ufw to apply the changes
sudo ufw reload

